//! VW-001 parity: byte-exact diff/patch vs the REAL Shared/mudb JS build.
//!
//! Fixtures are generated by `tools/parity/gen-fixtures.mjs` (Node) using the
//! vendored Shared/mudb in NEA-Project. Each case carries the schema.json, the
//! base/target values (JSON), and the expected diff bytes produced by the JS
//! reference. This test replays the same diff in Rust and asserts byte
//! equality, then patches base with the SAME bytes and asserts the result
//! equals target (patch round-trip).

use std::fs;

use voxweb_protocol::json::{schema_from_json, value_from_json};
use voxweb_protocol::{ReadStream, Schema, WriteStream};

struct Fixture {
    name: String,
    schema: Schema,
    base: voxweb_protocol::Value,
    target: voxweb_protocol::Value,
    changed: bool,
    diff_hex: String,
    frame: Option<(u32, u32)>, // (idBase, msgId) for message-frame cases
}

fn load_fixtures() -> Vec<Fixture> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tools/parity/fixtures/parity.json"
    );
    let raw = fs::read_to_string(path).expect("parity.json fixture file");
    let cases: Vec<serde_json::Value> =
        serde_json::from_str(&raw).expect("parity.json is valid JSON");
    let mut out = Vec::new();
    for c in cases {
        let schema = schema_from_json(&c["schema"]).expect("schema_from_json");
        let base_json = c.get("base").cloned().unwrap_or(serde_json::Value::Null);
        let target_json = c.get("target").cloned().unwrap_or(serde_json::Value::Null);
        let base = value_from_json(&schema, &base_json).expect("value_from_json base");
        let target = value_from_json(&schema, &target_json).expect("value_from_json target");
        let frame = c.get("frame").map(|f| {
            (
                f["idBase"].as_u64().unwrap_or(0) as u32,
                f["msgId"].as_u64().unwrap_or(0) as u32,
            )
        });
        out.push(Fixture {
            name: c["name"].as_str().unwrap_or("?").to_string(),
            schema,
            base,
            target,
            changed: c["changed"].as_bool().unwrap_or(false),
            diff_hex: c["diffHex"].as_str().unwrap_or("").to_string(),
            frame,
        });
    }
    out
}

fn run_diff(fixture: &Fixture) -> (bool, Vec<u8>) {
    let mut out = WriteStream::new(256);
    // message-frame cases: the expected bytes include the message-id varint
    if let Some((id_base, msg_id)) = fixture.frame {
        out.write_varint(id_base + msg_id);
    }
    let changed = fixture
        .schema
        .diff(&fixture.base, &fixture.target, &mut out);
    (changed, out.bytes.clone())
}

fn run_patch(fixture: &Fixture, diff_bytes: &[u8]) -> voxweb_protocol::Value {
    let mut inp = ReadStream::new(diff_bytes);
    fixture
        .schema
        .patch(&fixture.base, &mut inp)
        .expect("patch")
}

#[test]
fn parity_diff_bytes_match_js_reference() {
    let fixtures = load_fixtures();
    assert!(
        fixtures.len() >= 60,
        "expected >=60 fixtures, got {}",
        fixtures.len()
    );
    let mut failures: Vec<String> = Vec::new();
    for f in &fixtures {
        let (changed, bytes) = run_diff(f);
        let hex = hex_encode(&bytes);
        if changed != f.changed {
            failures.push(format!(
                "{}: changed flag mismatch rust={} js={}",
                f.name, changed, f.changed
            ));
            continue;
        }
        if hex != f.diff_hex {
            failures.push(format!(
                "{}: bytes mismatch\n  rust: {}\n  js:   {}",
                f.name, hex, f.diff_hex
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} parity diff mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn parity_patch_roundtrip_matches_target() {
    let fixtures = load_fixtures();
    let mut failures: Vec<String> = Vec::new();
    for f in &fixtures {
        if f.diff_hex.is_empty() {
            continue; // no bytes, nothing to patch
        }
        if f.frame.is_some() {
            continue; // frame payload patching is covered by the diff test below
        }
        let diff_bytes = hex_decode(&f.diff_hex);
        let patched = run_patch(f, &diff_bytes);
        if !f.schema.equal(&patched, &f.target) {
            failures.push(format!(
                "{}: patch result != target\n  patched: {:?}\n  target:  {:?}",
                f.name, patched, f.target
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} parity patch mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn parity_rust_diff_then_patch_roundtrip() {
    // Even where we haven't compared bytes, our own diff must patch back.
    let fixtures = load_fixtures();
    let mut failures: Vec<String> = Vec::new();
    for f in &fixtures {
        if f.frame.is_some() {
            continue; // frame bytes include the message-id varint; payload
                      // round-trip is already asserted by parity_patch_roundtrip_matches_target
        }
        let (_, bytes) = run_diff(f);
        if bytes.is_empty() {
            continue;
        }
        let patched = run_patch(f, &bytes);
        if !f.schema.equal(&patched, &f.target) {
            failures.push(format!(
                "{}: self roundtrip failed\n  patched: {:?}\n  target:  {:?}",
                f.name, patched, f.target
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} self-roundtrip mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn hex_decode(hex: &str) -> Vec<u8> {
    let mut out = Vec::with_capacity(hex.len() / 2);
    let bytes = hex.as_bytes();
    for i in (0..bytes.len()).step_by(2) {
        let hi = (bytes[i] as char).to_digit(16).unwrap_or(0);
        let lo = (bytes[i + 1] as char).to_digit(16).unwrap_or(0);
        out.push(((hi << 4) | lo) as u8);
    }
    out
}
