//! voxweb-protocol — byte-exact MuDB wire codec (Shared/mudb port).
//!
//! This crate implements the MuDB schema + stream semantics recovered from the
//! preserved NEA Player (Shared/mudb v1.0.1) so a Rust WASM client can speak
//! the same wire protocol as the preserved JS client. Parity with the JS
//! reference is verified by `tests/parity` (fixtures generated by
//! `tools/parity/gen-fixtures.mjs` from the real Shared/mudb build).

pub mod adapter;
pub mod atlas;
pub mod avatar_catalog;
pub mod avatar_part;
pub mod blockinfo;
pub mod browser;
pub mod driver;
pub mod geometry;
pub mod json;
pub mod netstate;
pub mod player;
pub mod protocol;
pub mod schema;
pub mod session;
pub mod session_web;
pub mod stream;
pub mod terrain;
pub mod ui;

pub use adapter::{
    nea_chunk_grid, nea_chunk_id_to_grid, set_nea_shape, voxweb_chunk_positions,
    write_voxweb_chunks, FALLBACK_NEA_WORLD,
};
pub use avatar_catalog::{AvatarCatalog, AvatarSkin, AVATAR_PART_NAMES};
pub use avatar_part::{decode_avatar_part, AvatarFace, AvatarPart, AvatarTexture};
pub use blockinfo::{texture_tile, BlockCatalog, BlockEntry, FaceMap};
pub use browser::BrowserSockets;
pub use driver::{SendFrame, SessionDriver, SessionStage};
pub use json::{schema_from_json, value_from_json};
pub use player::{
    camera_axis, eye_position, fps_camera, jump_velocity, jump_velocity_for, move_acceleration,
    move_speed, per_tick_displacement, qf, wire_angle, wire_camera_angle, wire_pitch, MoveMode,
    MovementFrame, INPUT_SWIM, PLAYER_CONFIG_PRECISION, PLAYER_HEIGHT, PLAYER_RADIUS, TICK_MS,
    TICK_SECONDS,
};
pub use protocol::{ParsedMessage, Protocol, ProtocolTable};
pub use schema::{Schema, Value};
pub use session::{
    RemoteClientEvent, SessionCtx, SessionHandlers, SessionTransport, TerrainChunk, TerrainReset,
};
pub use stream::{ReadStream, WriteStream};
pub use ui::{decode_dialog_open, decode_game_ui_reset, decode_gui_command, encode_runtime_outbound, DialogClose, DialogConfig, DialogOpen, DialogResult, GameUiState, GuiCommand, PictureAsset, UiCommon, UiCoord2, UiElement, UiNode, UiNodeValue, UiScreen};
